refactored pipeline

diff --git a/.tekton/tasks/aib-cmd.yaml b/.tekton/tasks/aib-cmd.yaml
--- a/.tekton/tasks/aib-cmd.yaml
+++ b/.tekton/tasks/aib-cmd.yaml
@@ -43,6 +43,12 @@ spec:
 
         echo "caib $(params.cmd)"
         caib $(params.cmd)
+        CAIB_EXIT_CODE=$?
+
+        if [ $CAIB_EXIT_CODE -ne 0 ]; then
+          echo "caib command failed with exit code $CAIB_EXIT_CODE"
+          exit $CAIB_EXIT_CODE
+        fi
 
   workspaces:
     - name: source
diff --git a/.tekton/tasks/aib-workspace-exec.yaml b/.tekton/tasks/aib-workspace-exec.yaml
--- a/.tekton/tasks/aib-workspace-exec.yaml
+++ b/.tekton/tasks/aib-workspace-exec.yaml
@@ -49,6 +49,12 @@ spec:
 
         # execute this command
         caib workspace exec $(params.workspace) -- $(params.cmd)
+        CAIB_EXIT_CODE=$?
+
+        if [ $CAIB_EXIT_CODE -ne 0 ]; then
+          echo "caib workspace exec failed with exit code $CAIB_EXIT_CODE"
+          exit $CAIB_EXIT_CODE
+        fi
 
   workspaces:
     - name: source
